/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import utils.DBConnection;
import utils.MyConnection;

/**
 *
 * @author Jyoti
 */
public class LoginPage extends javax.swing.JFrame {
    
    DBConnection conn;
    
    public LoginPage() {
        initComponents();
        conn = new DBConnection();
        if(conn==null){
       JOptionPane.showMessageDialog(this,"Database not connect", "Error", JOptionPane.ERROR_MESSAGE);
       }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfusername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfpassword = new javax.swing.JPasswordField();
        onclickbtnlogin = new javax.swing.JButton();
        onclickregister = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnhome = new javax.swing.JButton();
        onclickadminlogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        tfusername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");

        tfpassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        onclickbtnlogin.setBackground(new java.awt.Color(0, 0, 255));
        onclickbtnlogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        onclickbtnlogin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jyoti\\Desktop\\icons\\login.png")); // NOI18N
        onclickbtnlogin.setText("Login");
        onclickbtnlogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        onclickbtnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onclickbtnloginActionPerformed(evt);
            }
        });

        onclickregister.setBackground(new java.awt.Color(255, 0, 51));
        onclickregister.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        onclickregister.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jyoti\\Desktop\\icons\\register.png")); // NOI18N
        onclickregister.setText("Register");
        onclickregister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        onclickregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onclickregisterActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Student Login Form");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        btnhome.setBackground(new java.awt.Color(0, 204, 0));
        btnhome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnhome.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jyoti\\Desktop\\icons\\home-icon (1).png")); // NOI18N
        btnhome.setText("Home");
        btnhome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });

        onclickadminlogin.setBackground(new java.awt.Color(0, 0, 255));
        onclickadminlogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        onclickadminlogin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jyoti\\Desktop\\icons\\admin.png")); // NOI18N
        onclickadminlogin.setText("Admin Login");
        onclickadminlogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        onclickadminlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onclickadminloginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(onclickregister, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(onclickbtnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(onclickadminlogin))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfusername, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnhome)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfusername)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(onclickbtnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(onclickregister, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(onclickadminlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btnhome, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onclickbtnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onclickbtnloginActionPerformed
       String username = tfusername.getText();
       String password = tfpassword.getText();
       if(username.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Add A User Name");
        }
        else if(password.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Add A Password");
        }
        else{ 
        PreparedStatement ps, ps2;
        ResultSet rs ,rs2;
        
        String query = "SELECT * FROM student WHERE studentname =? AND password =?";
        
        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            ps2 = MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, username);
            ps.setString(2, password);
            ps2.setString(1, username);
            ps2.setString(2, password);
           
            rs = ps.executeQuery();
            
           rs2 = ps2.executeQuery();  
            if(rs.next())
            {
                    
                    StudentView sv = new StudentView();
                    sv.displayname.setText(username);
                    while(rs2.next()){
                    sv.displaycetscore.setText(rs2.getString("cetscore"));
                    sv.displayrank.setText(rs2.getString("ranking"));
                    sv.displaygender.setText(rs2.getString("gender"));
                    sv.displaypassword.setText(rs2.getString("password"));
                    sv.displayranking.setText("Your Ranking is "+ rs2.getString("ranking"));
                    StudentView.ranking1 = Integer.parseInt(rs2.getString("ranking"));
                    }
                    
                    sv.setVisible(true);
                    sv.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    this.dispose();
            }
            else{
                    JOptionPane.showMessageDialog(null, "Incorrect Username Or Password", "Login Failed", 2);
                }
            
        } catch (SQLException ex) {
            System.out.println(ex);
        }
                 
       
    }//GEN-LAST:event_onclickbtnloginActionPerformed
    }
    private void onclickregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onclickregisterActionPerformed
      RegisterPage r1 = new RegisterPage();
      r1.setVisible(true);
      r1.setLocationRelativeTo(null);
      this.dispose();

    }//GEN-LAST:event_onclickregisterActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnhomeActionPerformed

    private void onclickadminloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onclickadminloginActionPerformed
       String username = tfusername.getText();
       String password = tfpassword.getText();
       if(username.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Add A Admin Name");
        }
        else if(password.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Add A Password");
        }
        else{ 
        PreparedStatement ps, ps2;
        ResultSet rs ,rs2;
        
        String query = "SELECT * FROM admins WHERE adminname =? AND pass =?";
        
        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            ps2 = MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, username);
            ps.setString(2, password);
            ps2.setString(1, username);
            ps2.setString(2, password);
           
            rs = ps.executeQuery();
            
           rs2 = ps2.executeQuery();  
            if(rs.next())
            {
                    
               AdminView a1 = new AdminView();
                a1.setVisible(true);
                this.dispose();
            }
            else{
                    JOptionPane.showMessageDialog(null, "Incorrect Admin Name Or Password", "Login Failed", 2);
                }
            
        } catch (SQLException ex) {
            System.out.println(ex);
        }
                 
       
    }    
       
      /*  if(tfusername.getText().equals("rutwik") && tfpassword.getText().equals("rutwik"))
           {
               setVisible(false);
               AdminView a1 = new AdminView();
                a1.setVisible(true);
           }
           else
           {
               JOptionPane.showMessageDialog(null,"Incorrect Username or Password");
           }*/
    }//GEN-LAST:event_onclickadminloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton onclickadminlogin;
    private javax.swing.JButton onclickbtnlogin;
    private javax.swing.JButton onclickregister;
    private javax.swing.JPasswordField tfpassword;
    private javax.swing.JTextField tfusername;
    // End of variables declaration//GEN-END:variables

   
}